### ISSUE TITLE
Redis用Sentinel方式作主从切换， 工具连接异常！

### ISSUE THREAD

**Issue by glf14811** [caoxinyu/RedisClient#31]
1、Redis单个节点时， 工具连接正常
2、Redis采用主从Sentinel方式时， 该工具报异常：
redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketTimeoutException: Read timed out
        at redis.clients.jedis.Protocol.process(Protocol.java:135)
        at redis.clients.jedis.Protocol.read(Protocol.java:191)
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:175)
        at redis.clients.jedis.BinaryClient.connect(BinaryClient.java:78)
        at redis.clients.jedis.Connection.sendCommand(Connection.java:83)
        at redis.clients.jedis.Connection.sendCommand(Connection.java:79)
        at redis.clients.jedis.BinaryClient.auth(BinaryClient.java:533)
        at redis.clients.jedis.BinaryJedis.auth(BinaryJedis.java:2131)
        at com.cxy.redisclient.integration.JedisCommand.execute(JedisCommand.java:32)
        at com.cxy.redisclient.service.ServerService.listDBs(ServerService.java:101)
        at com.cxy.redisclient.presentation.RedisClient.serverTreeItemSelected(RedisClient.java:2761)
        at com.cxy.redisclient.presentation.RedisClient.treeItemSelected(RedisClient.java:2500)
        at com.cxy.redisclient.presentation.RedisClient.selectTreeItem(RedisClient.java:3275)
        at com.cxy.redisclient.presentation.RedisClient.access$2000(RedisClient.java:95)
        at com.cxy.redisclient.presentation.RedisClient$20.widgetSelected(RedisClient.java:616)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at com.cxy.redisclient.presentation.RedisClient.open(RedisClient.java:212)
        at com.cxy.redisclient.presentation.RedisClient.main(RedisClient.java:194)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at redis.clients.util.RedisInputStream.fill(RedisInputStream.java:109)
        at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:45)
        at redis.clients.jedis.Protocol.process(Protocol.java:120)
        ... 21 more

**Comment by GallantKong** [comment]
windows 64位已支持Sentinel
https://github.com/GallantKong/RedisClient
