### ISSUE TITLE
***WARNING: Display must be created on main thread due to Cocoa restrictions.

### ISSUE THREAD

**Issue by TamirTian** [caoxinyu/RedisClient#63]
`
***WARNING: Display must be created on main thread due to Cocoa restrictions.
Exception in thread "main" org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
	at org.eclipse.swt.widgets.Display.create(Unknown Source)
	at org.eclipse.swt.graphics.Device.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<init>(Unknown Source)
	at org.eclipse.swt.widgets.Display.getDefault(Unknown Source)
	at com.cxy.redisclient.presentation.RedisClient.open(RedisClient.java:204)
	at com.cxy.redisclient.presentation.RedisClient.main(RedisClient.java:194)
` 
java -XstartOnFirstThread -jar release/redisclient-OSX.jar 
在mac下需要增加-XstartOnFirstThread才能启动？

**Comment by caoxinyu** [comment]
是
