### ISSUE TITLE
不支持redis 4.0.1

### ISSUE THREAD

**Issue by kylixs** [caoxinyu/RedisClient#76]
双机展开redis时提示，“Redis服务器版本低，不支持此功能”

D:\downloads>java -jar redisclient-win32.x86_64.2.0.jar
java.lang.RuntimeException: Redis服务器版本低，不支持本功能。
        at com.cxy.redisclient.integration.JedisCommand.runCommand(JedisCommand.java:47)
        at com.cxy.redisclient.integration.JedisCommand.execute(JedisCommand.java:34)
        at com.cxy.redisclient.service.ServerService.listDBs(ServerService.java:101)
        at com.cxy.redisclient.presentation.RedisClient.serverTreeItemSelected(RedisClient.java:2761
)
        at com.cxy.redisclient.presentation.RedisClient.treeItemSelected(RedisClient.java:2500)
        at com.cxy.redisclient.presentation.RedisClient.selectTreeItem(RedisClient.java:3275)
        at com.cxy.redisclient.presentation.RedisClient.access$2000(RedisClient.java:95)
        at com.cxy.redisclient.presentation.RedisClient$20.widgetSelected(RedisClient.java:616)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at com.cxy.redisclient.presentation.RedisClient.open(RedisClient.java:212)
        at com.cxy.redisclient.presentation.RedisClient.main(RedisClient.java:194)

**Comment by caoxinyu** [comment]
请看这个
https://github.com/caoxinyu/RedisClient/issues/73
