### ISSUE TITLE
当链接Redis4.0时报错

### ISSUE THREAD

**Issue by huangbocom** [caoxinyu/RedisClient#79]
java.lang.RuntimeException: The version of redis server is too low to support th
is function.
        at com.cxy.redisclient.integration.JedisCommand.runCommand(JedisCommand.
java:47)
        at com.cxy.redisclient.integration.JedisCommand.execute(JedisCommand.jav
a:34)
        at com.cxy.redisclient.service.ServerService.listDBs(ServerService.java:
101)
        at com.cxy.redisclient.presentation.RedisClient.serverTreeItemSelected(R
edisClient.java:2761)
        at com.cxy.redisclient.presentation.RedisClient.addServer(RedisClient.ja
va:2321)
        at com.cxy.redisclient.presentation.RedisClient.access$5000(RedisClient.
java:95)
        at com.cxy.redisclient.presentation.RedisClient$56.widgetSelected(RedisC
lient.java:1402)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
        at com.cxy.redisclient.presentation.RedisClient.open(RedisClient.java:21
2)
        at com.cxy.redisclient.presentation.RedisClient.main(RedisClient.java:19
4)

**Comment by caoxinyu** [comment]
请使用这个
https://raw.githubusercontent.com/caoxinyu/RedisClient/windows/release/redisclient-win32.x86.2.0.exe
