### ISSUE TITLE
安装出错Cannot load 32-bit SWT libraries on 64-bit JVM电脑是MACOSX

### ISSUE THREAD

**Issue by daihu** [caoxinyu/RedisClient#8]
java -jar redisclient-linux.x86.1.5.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot load 32-bit SWT libraries on 64-bit JVM
    at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
    at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
    at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
    at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
    at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
    at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
    at com.cxy.redisclient.presentation.RedisClient.open(RedisClient.java:197)
    at com.cxy.redisclient.presentation.RedisClient.main(RedisClient.java:187)

**Comment by tjrafferty** [comment]
Having the same issue.
$ java -jar redisclient-linux.x86.1.5.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot load 32-bit SWT libraries on 64-bit JVM
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.internal.Converter.wcsToMbcs(Unknown Source)
	at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
	at com.cxy.redisclient.presentation.RedisClient.open(RedisClient.java:197)
	at com.cxy.redisclient.presentation.RedisClient.main(RedisClient.java:187)

**Comment by peter-liu** [comment]
ubuntu 14.04 64位没问题.

**Comment by heyongchenghithub** [comment]
How to resolve this problem?

**Comment by caoxinyu** [comment]
swt在macos上不好用，不推荐在macos上用redisclient

**Comment by timbersea** [comment]
在pom里替换成64位的依赖库就好了
<dependency>
    <groupId>org.eclipse.swt.org.eclipse.swt.gtk.linux.x86_64.4.3.swt</groupId>
    <artifactId>org.eclipse.swt.gtk.linux.x86_64</artifactId>
    <version>4.3</version>
</dependency>
